name: ml_dataframe
description: Dataframe - a way to store and manipulate data
version: 0.0.11
author: Ilia Gyrdymov <ilgyrd@gmail.com>
homepage: https://github.com/gyrdym/ml_dataframe

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  csv: ^4.0.0
  ml_linalg: ^12.0.2
  quiver: ^2.0.2

dev_dependencies:
  benchmark_harness: '>=1.0.0 <2.0.0'
  build_runner: ^1.1.2
  build_test: ^0.10.2
  grinder: ^0.8.3
  ml_tech: ^0.0.5
  mockito: ^3.0.0
  test: ^1.2.0
